### ISSUE TITLE
Can not install kimera-distributed and kimera-multi-lcd

### ISSUE THREAD

**Issue by YESAndy** [MIT-SPARK/Kimera-Multi#1]
Hi there,

Thank you for sharing this work! I met some problems when I am trying to vcs import 
```shell
=== ./kimera_distributed (git) ===
Could not determine ref type of version: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
=== ./kimera_multi_lcd (git) ===
Could not determine ref type of version: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
``` 

Could anyone help? Thank you!

**Comment by yunzc** [comment]
Hi @YESAndy,
Thank you for your interest in our work. 
Sorry that you encountered this issue. As mentioned in the README, some individual modules might not be online or fully updated yet, but will be online by April 5th! We will update that information if we are able to finish preparing and getting approval/figuring out the licensing for the realease sooner.
Thanks!
