### ISSUE TITLE
Running Kimera-Multi with multiple drones in Airsim and Unreal Engine

### ISSUE THREAD

**Issue by sandilyasg** [MIT-SPARK/Kimera-Multi#10]
Thanks for the great work. I am looking to simulate multi-robot SLAM using kimera-multi in a photorealistic scenario. At the moment I have found Airsim to be an excellent plugin for drones with RGB and depth streams in Unreal Engine. Can you give guidance on how to set up kimera-multi using this repo on airsim with UE? 
I am trying to understand how I can integrate Kimera-multi given that I have multiple rgb and depth streams from each agent. Roughly speaking, what kinds of inputs I would require (rgb stream, depth stream, odometry, etc.)

**Comment by yunzc** [comment]
Hi @sandilyasg! In general, you can follow our examples on using our provided dataset and set up your own launch files that feed rgb / imu to Kimera-VIO which would naturally feed into Kimera-Multi. 
Kimera-VIO can take RGBD-IMU or stereo-IMU, and can also optionally take in an external odometry source.

**Comment by sandilyasg** [comment]
Thanks for the reply @yunzc. I switched to using Unity because it was simpler to setup than UE4. I will post a feature on this git repo once I complete the implementation!

**Comment by DimitriosGkegkas** [comment]
Hi @sandilyasg,

I hope you're doing well. I saw your comments on the issue regarding the simulation of multi-robot SLAM using Kimera-Multi with Airsim and Unreal Engine. I'm currently working on a similar setup and was wondering if you managed to successfully configure it.

If so, could you please share the launch files and any other configurations or resources you used? It would be incredibly helpful for my project.

Thank you in advance!
