### ISSUE TITLE
Campus-Outdoor Data Testing and Custom YAML Configuration with Kimera-Multi

### ISSUE THREAD

**Issue by CSH-1220** [MIT-SPARK/Kimera-Multi#12]
Hello, I have a few questions .

Firstly, I have been working with the Campus-Outdoor data set for testing with Kimera-Multi. I've followed the instructions provided, running the command CATKIN_WS=<path-to-catkin-ws> DATA_PATH=<path-to-campus-outdoor-data-folder> LOG_DIR=<path-to-log-folder> tmuxp load 1014-example.yaml. Despite the process completing without any module errors, I am unable to visualize the robot's path in RViz. I have tried solutions mentioned in closed issues https://github.com/MIT-SPARK/Kimera-Multi-Data/issues/3, https://github.com/MIT-SPARK/Kimera-Multi-Data/issues/6, and https://github.com/MIT-SPARK/Kimera-Multi-Data/issues/8 on your repository, but the problem persists. I suspect an issue with the DPGO module, possibly related to loop closure detection. I have attached the log file from this run for your reference.

Secondly, I have created a custom YAML file, 1014-example-2robots.yaml, based on the original file logic, modifying it to operate with only two robots instead of six. However, I encounter an error during the execution of the second robot ( Total inter-robot loop closures: 0; DistributedLoopClosure.cpp:100] Check failed: robot_id >= config_.my_id_ (0 vs. 1)), which seems unexpected given the logical nature of the modifications. I am attaching this YAML file as well in the zip file and would greatly appreciate your insights into whether my approach is correct and what might be causing this error.

Thank you for your time and consideration.
[klog.zip](https://github.com/MIT-SPARK/Kimera-Multi/files/13330059/klog.zip)

**Comment by yunzc** [comment]
Hi, from a quick glance at your yaml and your logs:
I would check that the robot names and ids are assigned correctly [here](https://github.com/MIT-SPARK/Kimera-Distributed/blob/main/params/robot_names.yaml). This seems to match up with the error you got. For example, `acl_jackal2` should be with robot-id 1. My recommendation is to either create the two robot example with `acl_jackal` instead of `acl_jackal2` or make sure `acl_jackal2` is properly assigned to robot-id 0.
Same for `thoth` and its robot-id.

**Comment by zhuoyuan00** [comment]
Hi I also met the first problem while using Campus-Outdoor bag. Following the process in readme, it seems the code is running without mistake, but there is nothing can be shown in rviz. How to deal with it?
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/89250431/85fdb401-803b-4d13-beaf-1b696772c683)

**Comment by yunzc** [comment]
> Hi I also met the first problem while using Campus-Outdoor bag. Following the process in readme, it seems the code is running without mistake, but there is nothing can be shown in rviz. How to deal with it? ![image](https://private-user-images.githubusercontent.com/89250431/285377636-85fdb401-803b-4d13-beaf-1b696772c683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDI0MDIsIm5iZiI6MTcwMTEwMjEwMiwicGF0aCI6Ii84OTI1MDQzMS8yODUzNzc2MzYtODVmZGI0MDEtODAzYi00ZDEzLWJlYWYtMWI2OTY3NzJjNjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2MjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NmE5Y2UwZjE0OTY3Yjc5MjAxZDllZjRmODcwZDZmZjljMDA2ODNhMWVjNDYyMzJjYzBjODNmYmFkNDYxMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wmUqExd5_tS7SvQel2BT5veO8HJWou2eKuWbsD1uIqA)

Hi, could you try the solution mentioned here https://github.com/MIT-SPARK/Kimera-Multi/issues/3 and see if that helps?

**Comment by yunzc** [comment]
Close due to inactivity
