### ISSUE TITLE
process [acl_jackal/kimera_vio_ros/kimera_vio_ros_node-1] has died!

### ISSUE THREAD

**Issue by yongyun-iastate** [MIT-SPARK/Kimera-Multi#13]
Hello, I am facing that process [acl_jackal/kimera_vio_ros/kimera_vio_ros_node-1] has died! I guess it is because I don't have the rosbag files. How can I obtain your rosbag files?

<img width="1470" alt="Screenshot 2023-11-27 at 10 08 56 AM" src="https://github.com/MIT-SPARK/Kimera-Multi/assets/145062367/bd22482a-46e7-44d5-9605-abf4feeb28ec">

$tmuxp load src/kimera_multi/examples/1014-example.yaml 
[Loading] /root/catkin_ws/src/kimera_multi/examples/1014-example.yaml

 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/log_gt_data: True
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/map_frame_id: acl_jackal/map
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/mono_ransac_threshold: 30
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/odom_frame_id: acl_jackal/odom
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/online_run: True
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/params_folder_path: /root/catkin_ws/s...
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/position_det_threshold: 0.3
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/publish_vlc_frames: True
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/right_cam_frame_id: acl_jackal/forwar...
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/robot_id: 0
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/sensor_params_folder_path: 
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/stereo_ransac_threshold: 20
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/use_external_odom: True
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/use_lcd: True
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/use_lcd_registration_server: False
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/use_rviz: True
 * /acl_jackal/kimera_vio_ros/kimera_vio_ros_node/velocity_det_threshold: 0.1
 * /acl_jackal/use_sim_time: True
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /acl_jackal/
    base_to_realsense (tf2_ros/static_transform_publisher)
    left_img_decompress (image_transport/republish)
    right_img_decompress (image_transport/republish)
  /acl_jackal/kimera_vio_ros/
    kimera_vio_ros_node (kimera_vio_ros/kimera_vio_ros_node)

ROS_MASTER_URI=http://localhost:11311

process[acl_jackal/kimera_vio_ros/kimera_vio_ros_node-1]: started with pid [15397]
process[acl_jackal/base_to_realsense-2]: started with pid [15403]
process[acl_jackal/left_img_decompress-3]: started with pid [15410]
process[acl_jackal/right_img_decompress-4]: started with pid [15423]
================================================================================REQUIRED process [acl_jackal/kimera_vio_ros/kimera_vio_ros_node-1] has died!
process has died [pid 15397, exit code -11, cmd /root/catkin_ws/devel/lib/kimera_vio_ros/kimera_vio_ros_node --use_lcd=true --vocabulary_path=/root/catkin_ws/src/kimera_multi_lcd/vocab/mit_voc.yml --flagfile=/root/catkin_ws/src/kimera_multi/params/D455/flags/Mesher.flags --flagfile=/root/catkin_ws/src/kimera_multi/params/D455/flags/VioBackend.flags --flagfile=/root/catkin_ws/src/kimera_multi/params/D455/flags/RegularVioBackend.flags --flagfile=/root/catkin_ws/src/kimera_multi/params/D455/flags/Visualizer3D.flags --use_external_odometry=true --do_coarse_imu_camera_temporal_sync=false --do_fine_imu_camera_temporal_sync=false --lcd_no_optimize=true --lcd_no_detection=false --depth_image_mask= --logtostderr=1 --colorlogtostderr=1 --log_prefix=1 --minloglevel=0 --v=0 --log_output=false --log_euroc_gt_data=false --output_path=/root/catkin_ws/src/kimera_ros/output_logs/ --lcd_disable_stereo_match_depth_check=true --no_incremental_pose=true --viz_type=2 --visualize=true left_cam/image_raw:=/acl_jackal/forward/infra1/image_rect_raw left_cam/image_raw/compressed:=/acl_jackal/forward/infra1/image_rect_raw/compressed right_cam/image_raw:=/acl_jackal/forward/infra2/image_rect_raw right_cam/image_raw/compressed:=/acl_jackal/forward/infra2/image_rect_raw/compressed imu:=/acl_jackal/forward/imu external_odom:=/acl_jackal/jackal_velocity_controller/odom reinit_flag:=reinit_flag reinit_pose:=reinit_pose odometry:=odometry resiliency:=resiliency imu_bias:=imu_bias optimized_trajectory:=optimized_trajectory pose_graph:=pose_graph mesh:=mesh frontend_stats:=frontend_stats debug_mesh_img/image_raw:=debug_mesh_img/image_raw feature_tracks/image_raw:=feature_tracks/image_raw time_horizon_pointcloud:=time_horizon_pointcloud __name:=kimera_vio_ros_node __log:=/root/.ros/log/b6e6df30-8d3e-11ee-b884-0242ac110002/acl_jackal-kimera_vio_ros-kimera_vio_ros_node-1.log].
log file: /root/.ros/log/b6e6df30-8d3e-11ee-b884-0242ac110002/acl_jackal-kimera_vio_ros-kimera_vio_ros_node-1*.log
Initiating shutdown!
================================================================================
[acl_jackal/right_img_decompress-4] killing on exit
[acl_jackal/left_img_decompress-3] killing on exit
[acl_jackal/base_to_realsense-2] killing on exit
[acl_jackal/kimera_vio_ros/kimera_vio_ros_node-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by yunzc** [comment]
Hi, feel free to submit a request here: https://github.com/MIT-SPARK/Kimera-Multi-Data
