### ISSUE TITLE
Can not find kimera_vio_jackal.launch

### ISSUE THREAD

**Issue by leng-96** [MIT-SPARK/Kimera-Multi#2]
Hi there
Thank you for sharing this work! I met some problems when I am trying to CATKIN_WS=<path-to-catkin-ws> DATA_PATH=<path-to-campus-outdoor-data-folder> LOG_DIR=/home/yunchang/logs/kimera_distributed_10_14 tmuxp load 1014-example.yaml
 
There is a command on line 65 of this yaml file, roslaunch kimera_core kimera_vio_jackal.launch, but this file and kimera_core are not in the installed project。

Could anyone help? Thank you!

**Comment by yunzc** [comment]
Good catch. I missed that when making the system public. Let me fix that.

**Comment by yunzc** [comment]
Updated the example

**Comment by leng-96** [comment]
thinks
