### ISSUE TITLE
Problems encountered with rviz simulation

### ISSUE THREAD

**Issue by ToothlessOS** [MIT-SPARK/Kimera-Multi#27]
Firstly, I would like to express my appreciation your sharing of the awesome work!

I was encountering some issues with the Rviz simulation:
1. No visualization available in Rviz with the warning of 'no tf data'
![Screenshot from 2024-06-30 10-36-33](https://github.com/MIT-SPARK/Kimera-Multi/assets/144514251/aec5e526-efaa-47f4-924b-432c79b9948b)
2. The rosbag players only keep outputting messages like the following then quits directly:
![Screenshot from 2024-06-30 10-40-33](https://github.com/MIT-SPARK/Kimera-Multi/assets/144514251/fcc04619-e986-45b3-85a3-a5883e6ef9cb)
3. Based on the solution of some other issues, I tried to check the log. However, I found there were no log available.
![Screenshot from 2024-06-30 10-41-23](https://github.com/MIT-SPARK/Kimera-Multi/assets/144514251/81173267-533c-44ad-9a7a-0e50f0bdb50f)

Could you please offer some advice on resolving these issues? Many thanks!

**Comment by yunzc** [comment]
Has this issue been resolved? I would double check if the rosbags were downloaded and decompressed correctly.
