### ISSUE TITLE
Ubuntu 18.04 has no cmake 3.16

### ISSUE THREAD

**Issue by RonghaiHe** [MIT-SPARK/Kimera-Multi#34]
cmake 3.10 is the latest version on Ubuntu 18.04 based on `apt` while cmake 3.16 is required as the minimum version in `pose_graph_tools`.

So may I deploy `kimera-multi` on Ubuntu18.04 that were once done on Ubuntu 18.04 and ROS Melody mentioned in `README.md`?

**Comment by RonghaiHe** [comment]
In addition, some repositories at the `master` node have been updated and may not support Ubuntu18.04 now. Maybe it need to specify a specific node instead of `master`.

**Comment by LimHyungTae** [comment]
Yep, unfortunately, Ubuntu 18.04 is too low version. What do you think about upgrading your Ubuntu version?

Sooner or later, we gonna change all codes to ROS2, so I'd like to say that persisting on Ubuntu 18.04 is not a good idea.

**Comment by RonghaiHe** [comment]
You're right, and thanks for keeping update the code.
Maybe it would be better if you could set a specific branch for certain version like Ubuntu 18.04, 20.04 and ROS1, since you have mentioned them in README.md.

**Comment by yunzc** [comment]
Updated README to explicitly state 20.04 assumption for now.
