### ISSUE TITLE
Kimera-VIO version

### ISSUE THREAD

**Issue by RonghaiHe** [MIT-SPARK/Kimera-Multi#35]
Is it too old to use version `prerelease` in `Kimera-VIO` instead of `master`?

**Comment by RonghaiHe** [comment]
For example, this [code](https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/d13b7b94cf4bc99bf9ed35b09163850463f4ed8d/src/KimeraVioRos.cpp#L68) in `Kimera-VIO-ROS`:

```C++
vio_params_ = std::make_shared<VioParams>(params_path, sensor_params_path);
```

This is OK if using the `master` branch in `Kimera-VIO`. However, in the `feature/prerelease` branch, there are no such constructor with 2 parameters.

**Comment by yunzc** [comment]
Thanks for the catch! Updated.
